const ANIMALS = [
  {
    id: "huntsman", name: "Huntsman Spider", emoji: "🕷️",
    danger: 3, dangerLabel: "mildly dangerous",
    description: "Australia's largest spider – scarier looking than it actually is.",
    regions: { QLD: 92, NSW: 88, VIC: 72, SA: 65, WA: 78, NT: 85, TAS: 30, ACT: 60 },
    urban: 85, rural: 75,
    coastalOnly: false, marineOnly: false,
    seasons: { summer: 90, autumn: 70, winter: 40, spring: 80 },
    mating: "October – January", active: "Year-round, peak in summer",
    warning: "A bite causes local pain and swelling – not lethal, but unpleasant. They love hiding behind sun visors in cars. Always check before driving.",
    funFact: "A huntsman can run at 1 metre per second. And yes, they can drop from the ceiling directly onto you.",
    spotting: [
      { icon: "🕐", tip: "Check at night — huntsmans become active after dark and are much easier to spot with a torch." },
      { icon: "🏠", tip: "Look behind picture frames, curtains, and inside shoes. They love warm, sheltered spots indoors." },
      { icon: "🌳", tip: "Outside, check under loose bark on eucalyptus trees — a classic huntsman hideout." },
    ],
  },
  {
    id: "funnel_web", name: "Funnel-web Spider", emoji: "🕸️",
    danger: 5, dangerLabel: "EXTREMELY DANGEROUS",
    description: "One of the world's most venomous spiders. The Sydney funnel-web is legendary.",
    regions: { QLD: 60, NSW: 95, VIC: 20, SA: 5, WA: 2, NT: 10, TAS: 5, ACT: 70 },
    urban: 60, rural: 70,
    coastalOnly: false, marineOnly: false,
    seasons: { summer: 95, autumn: 60, winter: 20, spring: 70 },
    mating: "January – March (males roam for females)", active: "Summer – especially after rain",
    warning: "Call emergency services IMMEDIATELY if bitten. Apply a pressure bandage. Since antivenom was introduced in 1981, no deaths have occurred – but you must act FAST.",
    funFact: "The male is 6× more venomous than the female – a rarity in the animal kingdom. Their venom is more toxic to humans than to other primates.",
    spotting: [
      { icon: "🌧️", tip: "Go out the morning after heavy rain — males leave their burrows to find mates and are most visible then." },
      { icon: "🪨", tip: "Look for silk-lined burrows with trip-lines radiating outward under rocks, logs, or dense shrubs." },
      { icon: "👟", tip: "Always shake out shoes, gloves, and towels left outside — funnel-webs hide in dark, enclosed spaces." },
    ],
  },
  {
    id: "saltwater_croc", name: "Saltwater Crocodile", emoji: "🐊",
    danger: 5, dangerLabel: "DEADLY",
    description: "The world's largest reptile. Completely at home in northern Australia.",
    regions: { QLD: 75, NSW: 5, VIC: 0, SA: 0, WA: 60, NT: 98, TAS: 0, ACT: 0 },
    urban: 15, rural: 85,
    coastalOnly: true, marineOnly: false,
    seasons: { summer: 95, autumn: 70, winter: 50, spring: 80 },
    mating: "September – October", active: "Year-round – more aggressive in warmer months",
    warning: "Never swim in marked croc areas! Saltwater crocs can lurk near ocean beaches too. Take every 'Croc Country' sign SERIOUSLY.",
    funFact: "Saltwater crocs can live over 70 years and weigh up to 1,000 kg. They have the strongest bite force of any living animal.",
    spotting: [
      { icon: "🌅", tip: "Early morning and late afternoon — crocs bask on riverbanks to warm up. Binoculars strongly recommended." },
      { icon: "🚤", tip: "Guided boat tours on the Adelaide or Daintree River offer safe, close-up sightings with expert commentary." },
      { icon: "👁️", tip: "Scan the water's edge for eyes and nostrils just above the surface — crocs are masters of stillness." },
    ],
  },
  {
    id: "freshwater_croc", name: "Freshwater Crocodile", emoji: "🐊",
    danger: 2, dangerLabel: "low risk",
    description: "The smaller cousin – only attacks when disturbed.",
    regions: { QLD: 80, NSW: 0, VIC: 0, SA: 0, WA: 70, NT: 95, TAS: 0, ACT: 0 },
    urban: 10, rural: 80,
    coastalOnly: false, marineOnly: false,
    seasons: { summer: 85, autumn: 65, winter: 45, spring: 75 },
    mating: "August – September", active: "Year-round",
    warning: "Won't bite unless provoked. Still – keep your distance.",
    funFact: "Freshwater crocs are excellent swimmers and can survive dry seasons buried in mud.",
    spotting: [
      { icon: "☀️", tip: "Mid-morning is ideal — freshies bask on sandy riverbanks after the cool night to warm up." },
      { icon: "🏞️", tip: "Look along inland rivers, gorges, and billabongs in the NT and north QLD. Windjana Gorge is a hotspot." },
      { icon: "🔦", tip: "Night spotting by boat is very effective — use a torch to catch the orange eyeshine reflecting off the water." },
    ],
  },
  {
    id: "kangaroo", name: "Kangaroo", emoji: "🦘",
    danger: 1, dangerLabel: "generally safe",
    description: "Australia's iconic symbol. You'll find them almost everywhere.",
    regions: { QLD: 90, NSW: 95, VIC: 88, SA: 85, WA: 80, NT: 75, TAS: 60, ACT: 95 },
    urban: 60, rural: 98,
    coastalOnly: false, marineOnly: false,
    seasons: { summer: 75, autumn: 85, winter: 90, spring: 88 },
    mating: "Year-round", active: "Dawn and dusk",
    warning: "Watch out when driving at dusk! A kangaroo on the highway is a very real danger. Never chase a large male – it can kick with 500 kg of force.",
    funFact: "Kangaroos can't walk backwards. That's why they're on the Australian coat of arms – symbolising moving forward.",
    spotting: [
      { icon: "🌄", tip: "Go out at dawn or dusk — mobs gather in open grassland and golf courses to graze when it's cooler." },
      { icon: "🌿", tip: "Look at field edges next to bushland. Kangaroos shelter in the shade during the heat of the day." },
      { icon: "🚗", tip: "Drive slowly on rural roads at dusk — you'll spot them in the headlights. Pull over safely and watch from the car." },
    ],
  },
  {
    id: "camel", name: "Feral Camel", emoji: "🐪",
    danger: 1, dangerLabel: "generally safe",
    description: "Yes, over a million wild camels roam Australia. The British brought them.",
    regions: { QLD: 40, NSW: 20, VIC: 5, SA: 75, WA: 80, NT: 90, TAS: 0, ACT: 0 },
    urban: 5, rural: 70,
    coastalOnly: false, marineOnly: false,
    seasons: { summer: 60, autumn: 70, winter: 75, spring: 70 },
    mating: "June – September", active: "Year-round",
    warning: "Males in rut are aggressive. Camels can kick in all directions – keep your distance.",
    funFact: "Australia exports camels to the Arabian Peninsula – it's the only country with a population of truly wild dromedaries.",
    spotting: [
      { icon: "🛩️", tip: "The best way to see large mobs is from a scenic flight over the NT or SA outback — herds of hundreds are common." },
      { icon: "💧", tip: "Find them near waterholes in the dry season — camels need to drink every few days in extreme heat." },
      { icon: "🌵", tip: "Drive the Oodnadatta Track or Gibb River Road slowly at dawn — camels cross roads and are hard to spot." },
    ],
  },
  {
    id: "koala", name: "Koala", emoji: "🐨",
    danger: 1, dangerLabel: "generally safe",
    description: "Sleeps 18–22 hours a day. Eats only eucalyptus leaves.",
    regions: { QLD: 75, NSW: 80, VIC: 70, SA: 50, WA: 10, NT: 5, TAS: 0, ACT: 60 },
    urban: 45, rural: 80,
    coastalOnly: false, marineOnly: false,
    seasons: { summer: 60, autumn: 75, winter: 70, spring: 85 },
    mating: "October – February", active: "Nocturnal (rarely seen during the day)",
    warning: "Don't cuddle wild koalas! They have sharp claws and bite harder than you'd expect. They are wild animals, not stuffed toys.",
    funFact: "Koalas have fingerprints virtually indistinguishable from human ones – even forensic scientists struggle to tell them apart.",
    spotting: [
      { icon: "🌳", tip: "Look up into the forks of eucalyptus trees — koalas wedge themselves in and are easy to miss. Scan trunks for scratch marks." },
      { icon: "👂", tip: "In mating season (Oct–Feb), listen for the male's loud belching bellow — it's unmistakable and carries far." },
      { icon: "🌧️", tip: "After rain, koalas come down from trees to drink and are much easier to spot at ground level." },
    ],
  },
  {
    id: "cockatoo", name: "Sulphur-crested Cockatoo", emoji: "🦜",
    danger: 1, dangerLabel: "generally safe",
    description: "Loud, intelligent, and everywhere. An Australian classic.",
    regions: { QLD: 90, NSW: 92, VIC: 85, SA: 70, WA: 75, NT: 80, TAS: 65, ACT: 88 },
    urban: 90, rural: 85,
    coastalOnly: false, marineOnly: false,
    seasons: { summer: 80, autumn: 85, winter: 75, spring: 90 },
    mating: "August – January", active: "Daytime",
    warning: "A flock of cockatoos can destroy a wooden deck or roof in a few hours. That beak is a serious tool.",
    funFact: "Cockatoos can live up to 80 years. They're so intelligent they get bored – and then start destroying things for fun.",
    spotting: [
      { icon: "👂", tip: "You'll hear them before you see them — a screeching flock is unmistakable. Just follow the noise." },
      { icon: "🌅", tip: "Morning and late afternoon are peak feeding times. Look in grassy parks, sports fields, and farmland." },
      { icon: "🌳", tip: "At dusk, large flocks gather in roosting trees and make an extraordinary spectacle — find a tall gum tree near water." },
    ],
  },
  {
    id: "brown_snake", name: "Eastern Brown Snake", emoji: "🐍",
    danger: 5, dangerLabel: "DEADLY",
    description: "The world's second most venomous snake. Responsible for most snakebite deaths in Australia.",
    regions: { QLD: 90, NSW: 95, VIC: 80, SA: 75, WA: 40, NT: 60, TAS: 10, ACT: 85 },
    urban: 55, rural: 92,
    coastalOnly: false, marineOnly: false,
    seasons: { summer: 95, autumn: 65, winter: 15, spring: 88 },
    mating: "September – October", active: "Spring–Summer, during the day",
    warning: "Call emergency services immediately. Apply a pressure bandage over the full limb. DO NOT MOVE – movement speeds venom absorption. Do not attempt to catch the snake.",
    funFact: "The eastern brown snake can strike up to 12 times in a single encounter. Despite this, with proper treatment, fatalities are rare.",
    spotting: [
      { icon: "☀️", tip: "Mid-morning on warm spring days — brown snakes bask on open ground to raise their body temperature after cool nights." },
      { icon: "👣", tip: "Walk heavily and loudly on bush tracks. Snakes feel vibrations and usually flee well before you see them." },
      { icon: "🌾", tip: "Check around sheds, hay bales, and long grass on rural properties — brown snakes hunt mice in these areas." },
    ],
  },
  {
    id: "shark", name: "Great White Shark", emoji: "🦈",
    danger: 4, dangerLabel: "dangerous",
    description: "The apex predator of Australian waters.",
    regions: { QLD: 60, NSW: 75, VIC: 65, SA: 80, WA: 85, NT: 30, TAS: 70, ACT: 0 },
    urban: 40, rural: 60,
    coastalOnly: true, marineOnly: true,
    seasons: { summer: 85, autumn: 70, winter: 55, spring: 75 },
    mating: "October – January", active: "Year-round, most active at dawn and dusk",
    warning: "Swim at patrolled beaches within the flags. Avoid swimming at dawn, dusk, and night. Open wounds in the water are a very bad idea.",
    funFact: "Australia is one of the world's most shark-attack-prone countries – yet you're statistically more likely to be killed by a kangaroo (via car collision).",
    spotting: [
      { icon: "🛶", tip: "Cage diving tours in Port Lincoln (SA) offer guaranteed sightings — great whites aggregate around seal colonies nearby." },
      { icon: "🦭", tip: "Look near seal and sea lion colonies — great whites patrol these areas regularly. Keep a safe distance from the water." },
      { icon: "🚁", tip: "Surf Life Saving drones patrol popular beaches in NSW and QLD — follow their social media for recent sighting reports." },
    ],
  },
  {
    id: "wombat", name: "Wombat", emoji: "🦡",
    danger: 1, dangerLabel: "generally safe",
    description: "Stocky, adorable, produces cube-shaped droppings. Seriously.",
    regions: { QLD: 40, NSW: 75, VIC: 80, SA: 60, WA: 20, NT: 5, TAS: 85, ACT: 70 },
    urban: 30, rural: 85,
    coastalOnly: false, marineOnly: false,
    seasons: { summer: 60, autumn: 75, winter: 80, spring: 70 },
    mating: "Year-round", active: "Nocturnal",
    warning: "A wombat is stronger than it looks – 35 kg of pure muscle. Chase one into its burrow and it can crush you against the ceiling. This has actually happened.",
    funFact: "The wombat is the only animal that produces cubic faeces. Scientists only recently figured out how – using a soft intestine with variable stiffness.",
    spotting: [
      { icon: "🌙", tip: "Go out just after dark with a red-filtered torch — red light doesn't disturb them as much as white light." },
      { icon: "🕳️", tip: "Find their burrows during the day (look for large mounds of disturbed earth) and wait quietly nearby at dusk." },
      { icon: "❄️", tip: "Winter is best — wombats emerge earlier in the evening because the nights are longer and it cools down faster." },
    ],
  },
  {
    id: "dingo", name: "Dingo", emoji: "🐕",
    danger: 2, dangerLabel: "low risk",
    description: "Australia's wild dog. Famous line: 'A dingo ate my baby!'",
    regions: { QLD: 85, NSW: 75, VIC: 50, SA: 80, WA: 85, NT: 95, TAS: 5, ACT: 40 },
    urban: 20, rural: 88,
    coastalOnly: false, marineOnly: false,
    seasons: { summer: 75, autumn: 80, winter: 70, spring: 85 },
    mating: "April – June", active: "Dawn and dusk",
    warning: "Never feed a dingo! It causes them to lose their fear of humans. On Fraser Island dingoes are known to be aggressive – report every encounter.",
    funFact: "The dingo arrived in Australia about 4,000 years ago with Asian traders. It likely caused the extinction of the thylacine on the mainland.",
    spotting: [
      { icon: "🏖️", tip: "Fraser Island (K'gari) in QLD has the purest dingo population in Australia — walk the beaches at dawn for the best chance." },
      { icon: "🌅", tip: "Dawn and dusk along outback tracks — dingoes are crepuscular and often trot along roads in remote areas." },
      { icon: "🔇", tip: "Stay quiet and still. Dingoes are curious by nature and will often approach if you don't make sudden movements." },
    ],
  },
  {
    id: "wallaby", name: "Wallaby", emoji: "🦘",
    danger: 1, dangerLabel: "generally safe",
    description: "The kangaroo's smaller cousin. Cuter, less dangerous.",
    regions: { QLD: 85, NSW: 88, VIC: 82, SA: 70, WA: 75, NT: 65, TAS: 90, ACT: 80 },
    urban: 50, rural: 90,
    coastalOnly: false, marineOnly: false,
    seasons: { summer: 70, autumn: 80, winter: 85, spring: 88 },
    mating: "Year-round", active: "Dawn and dusk",
    warning: "Same road risk as kangaroos at dusk – wallabies are smaller and harder to spot.",
    funFact: "Wallabies can pause embryo development (embryonic diapause) – a joey waits as a dormant embryo until the pouch is free.",
    spotting: [
      { icon: "🌿", tip: "Look at the edges of bushland and rainforest — wallabies prefer denser cover than kangaroos and are shyer." },
      { icon: "🌄", tip: "Just after sunrise, check grassy clearings adjacent to forest. They graze briefly then retreat to shade." },
      { icon: "🏕️", tip: "Many national park campsites are visited by wallabies at dusk — sit quietly outside your tent and wait." },
    ],
  },
  {
    id: "tasmanian_devil", name: "Tasmanian Devil", emoji: "😈",
    danger: 2, dangerLabel: "low risk",
    description: "The world's largest carnivorous marsupial. Eats everything, including bones.",
    regions: { QLD: 0, NSW: 0, VIC: 0, SA: 0, WA: 0, NT: 0, TAS: 95, ACT: 0 },
    urban: 20, rural: 90,
    coastalOnly: false, marineOnly: false,
    seasons: { summer: 65, autumn: 80, winter: 70, spring: 85 },
    mating: "February – June", active: "Nocturnal",
    warning: "Don't linger near a Tasmanian devil at a carcass – it will defend its food with teeth and claws.",
    funFact: "The Tasmanian devil has one of the strongest bites relative to body size of any mammal. It suffers from a contagious facial tumour disease (DFTD) spread through biting.",
    spotting: [
      { icon: "🌙", tip: "Drive rural roads in Tasmania slowly after dark — devils scavenge roadkill and are regularly seen on roadsides." },
      { icon: "👂", tip: "Listen for their eerie screams at night — groups gather noisily around carcasses and can be heard from far away." },
      { icon: "🦘", tip: "Narawntapu National Park and the northwest coast of Tasmania have the highest densities for wild sightings." },
    ],
  },
  {
    id: "emu", name: "Emu", emoji: "🦤",
    danger: 2, dangerLabel: "low risk",
    description: "The world's second largest bird. Can't fly, but runs at 50 km/h.",
    regions: { QLD: 85, NSW: 88, VIC: 75, SA: 82, WA: 90, NT: 85, TAS: 10, ACT: 65 },
    urban: 25, rural: 92,
    coastalOnly: false, marineOnly: false,
    seasons: { summer: 65, autumn: 75, winter: 85, spring: 80 },
    mating: "April – June", active: "Daytime",
    warning: "Emus can kick forward with tremendous force. Never chase one – in 1932, the Australian army famously lost a war against emus.",
    funFact: "The Great Emu War of 1932 – the Australian military with machine guns vs. 20,000 emus. The emus won. Major Meredith compared them to Zulus, each needing five bullets.",
    spotting: [
      { icon: "🌾", tip: "Open grassland, farmland, and scrubland in the morning — emus walk great distances daily and are hard to miss at 1.9 m tall." },
      { icon: "💧", tip: "Find a waterhole in dry areas and wait — emus must drink daily and will walk kilometres to do so." },
      { icon: "🚗", tip: "Driving through outback WA, SA, and QLD you're almost certain to spot them — they're fearless around slow-moving vehicles." },
    ],
  },
  {
    id: "magpie", name: "Australian Magpie", emoji: "🐦",
    danger: 2, dangerLabel: "seasonal risk",
    description: "Australia's most feared bird during nesting season. It will swoop.",
    regions: { QLD: 90, NSW: 95, VIC: 92, SA: 85, WA: 80, NT: 60, TAS: 75, ACT: 95 },
    urban: 95, rural: 85,
    coastalOnly: false, marineOnly: false,
    seasons: { summer: 40, autumn: 30, winter: 20, spring: 98 },
    mating: "August – October (swoops during nesting!)", active: "Daytime",
    warning: "In spring: wear sunglasses or a bike helmet! Magpies target eyes. There's even a crowd-sourced attack map: magpiealert.com",
    funFact: "Magpies remember individual human faces for years. If you've been kind, they'll sing for you. If not… you already know.",
    spotting: [
      { icon: "🏙️", tip: "You don't need to look far — magpies are in almost every park, suburb, and school oval in Australia." },
      { icon: "🌅", tip: "Early morning is when they sing most actively. Their carolling is one of Australia's most beautiful sounds." },
      { icon: "🤝", tip: "To make friends with a local magpie: offer a small piece of cheese or mince, make eye contact, and visit daily. They'll remember you." },
    ],
  },
  {
    id: "box_jellyfish", name: "Box Jellyfish", emoji: "🪼",
    danger: 5, dangerLabel: "DEADLY",
    description: "The world's most venomous marine creature. Found in northern Australia in summer.",
    regions: { QLD: 90, NSW: 20, VIC: 5, SA: 5, WA: 60, NT: 95, TAS: 0, ACT: 0 },
    urban: 50, rural: 50,
    coastalOnly: true, marineOnly: true,
    seasons: { summer: 98, autumn: 50, winter: 5, spring: 60 },
    mating: "September – October", active: "Summer (October – April)",
    warning: "In northern Australia, NEVER swim without a stinger suit during season! Vinegar neutralises the tentacles – keep it on the beach. Death can occur within 2 minutes.",
    funFact: "Box jellyfish have 24 eyes (in 4 clusters of 6) – despite having no brain. They see the world around them in 360°.",
    spotting: [
      { icon: "🤿", tip: "Snorkelling at sheltered beaches in the NT and far north QLD outside stinger season (May–Sep) gives safe viewing opportunities." },
      { icon: "🔦", tip: "They are attracted to lights at night — shine a torch into calm, shallow water near the shore after dark." },
      { icon: "🧪", tip: "Marine research stations in Cairns and Darwin occasionally run guided night walks where scientists demonstrate safe identification." },
    ],
  },
];
